<a href="https://colab.research.google.com/github/jami-sriya17/NASSCOM/blob/main/Assignment-03_5e4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

def section_header(title):
    print("\n" + "=" * 60)
    print(title)
    print("=" * 60)


# ---------------------------------------------------------------
# 1. Creating Matrices and Vectors
# ---------------------------------------------------------------
def example_create_arrays():
    section_header("1. Creating Matrices and Vectors")

    v = np.array([1, 2, 3])
    A = np.array([[1, 2], [3, 4]])
    I = np.eye(3)          # identity matrix
    Z = np.zeros((2, 3))
    O = np.ones((3, 2))

    print("Vector v:\n", v)
    print("Matrix A:\n", A)
    print("Identity I:\n", I)
    print("Zeros Z:\n", Z)
    print("Ones O:\n", O)


# Exercises:
# 1a. Create a 4x4 identity matrix and print it.
# 1b. Create a 3x3 matrix filled with the number 7 (hint: np.full).
# 1c. Create a vector of 10 evenly spaced numbers between 0 and 1
#     (hint: np.linspace).
#
# --- your code here ---
A = np.eye(4)
print("Matrix 1a:\n", A)
B = np.full((3, 3), 7)
print("Matrix 1b:\n", B)
C = np.linspace(0, 1, 10)
print("Vector 1c:\n", C)

# ---------------------------------------------------------------
# 2. Matrix Multiplication
# ---------------------------------------------------------------
def example_matrix_multiplication():
    section_header("2. Matrix Multiplication")

    A = np.array([[1, 2], [3, 4]])
    B = np.array([[5, 6], [7, 8]])

    elementwise = A * B          # element-wise multiplication
    matmul_operator = A @ B      # matrix multiplication (preferred)
    matmul_function = np.matmul(A, B)
    dot_function = np.dot(A, B)

    print("A:\n", A)
    print("B:\n", B)
    print("Element-wise A*B:\n", elementwise)
    print("Matrix mult A@B:\n", matmul_operator)
    print("np.matmul(A, B):\n", matmul_function)
    print("np.dot(A, B):\n", dot_function)


# Exercises:
# 2a. Given A = [[2, 0], [0, 2]] and B = [[1, 2], [3, 4]], compute A@B
#     by hand, then verify with NumPy.
# 2b. Multiply a 3x2 matrix by a 2x4 matrix. What shape is the result?
# 2c. Explain (in a comment) why A*B and A@B give different results.
#
# --- your code here ---
A = np.array([[2, 0], [0, 2]])
B = np.array([[1, 2], [3, 4]])
print("Matrix 2a:\n", A @ B)
C = np.array([[7,8],[9,10],[11,12]])
D = np.array([[1,2,3,4],[5,6,7,8]])
result_2b = C @ D
print("Matrix 2b:\n", C @ D)
print("Shape of the result 2b\n",result_2b.shape)
#2c. Explain (in a comment) why A*B and A@B give different results.
# A*B performs element-wise multiplication (Hadamard product), meaning it multiplies
# corresponding elements in two arrays of the same shape. For example, the element
# at (0,0) in the result is the product of element A(0,0) and B(0,0).
# A@B performs matrix multiplication, which follows the rules of linear algebra.
# For matrix multiplication, the number of columns in the first matrix must equal
# the number of rows in the second matrix. The elements of the resulting matrix
# are computed as dot products of rows from the first matrix and columns from the second.

# ---------------------------------------------------------------
# 3. Transpose
# ---------------------------------------------------------------
def example_transpose():
    section_header("3. Transpose")

    A = np.array([[1, 2, 3], [4, 5, 6]])
    print("A:\n", A)
    print("A.T (transpose):\n", A.T)
    print("np.transpose(A):\n", np.transpose(A))


# Exercises:
# 3a. Create a 3x5 matrix and confirm its transpose has shape (5, 3).
# 3b. Verify that (A @ B).T equals B.T @ A.T for two matrices A, B.
#
# --- your code here ---
A = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]])
print("Matrix 3a:\n", A)
print("Transpose of Matrix 3a:\n", A.T)
print("Shape of transpose matrix 3a:\n", A.T.shape)
print("Matrix 3b:\n", (A @ B).T)
print("Shape of (A @ B).T:\n", (A @ B).T.shape)
print("B.T @ A.T:\n", B.T @ A.T)
print("Shape of B.T @ A.T:\n", (B.T @ A.T).shape)

# ---------------------------------------------------------------
# 4. Determinant
# ---------------------------------------------------------------
def example_determinant():
    section_header("4. Determinant")

    A = np.array([[4, 2], [7, 6]])
    det = np.linalg.det(A)
    print("A:\n", A)
    print("Determinant of A:\n", det)


# Exercises:
# 4a. Compute the determinant of a 3x3 matrix of your choice.
# 4b. Create a singular (non-invertible) matrix and show its
#     determinant is (approximately) zero.
#
# --- your code here ---
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
det = np.linalg.det(A)
print("Matrix 4a:\n", A)
print("Determinant of Matrix 4a:\n", det)

B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 1]])
det = np.linalg.det(B)
print("Matrix 4b:\n", B)
print("Determinant of Matrix 4b:\n", det)

# ---------------------------------------------------------------
# 5. Matrix Inverse
# ---------------------------------------------------------------
def example_inverse():
    section_header("5. Matrix Inverse")

    A = np.array([[4, 7], [2, 6]])
    A_inv = np.linalg.inv(A)
    identity_check = A @ A_inv

    print("A:\n", A)
    print("Inverse of A:\n", A_inv)
    print("A @ A_inv (should be identity):\n", identity_check)


# Exercises:
# 5a. Try to invert a singular matrix and observe the error NumPy
#     raises (hint: wrap in try/except).
# 5b. Verify that (A_inv)_inv == A for a matrix of your choice.
#
# --- your code here ---
A = np.array([[1, 2], [3, 4]])
try:
    A_inv = np.linalg.inv(A)
except np.linalg.LinAlgError as e:
    print("Error:\n", e)
print("Matrix 5a:\n", A)
print("Inverse of Matrix 5a:\n", A_inv)

# Using a non-singular matrix for 5b to avoid LinAlgError
B = np.array([[4, 7], [2, 6]]) # Example from example_inverse, which is non-singular
B_inv = np.linalg.inv(B)
B_inv_inv = np.linalg.inv(B_inv)
print("Matrix 5b:\n", B)
print("Inverse of Matrix 5b:\n", B_inv)
print("Inverse of Inverse of Matrix 5b:\n", B_inv_inv)

# Verify (B_inv)_inv == B
print("Check (B_inv)_inv == B:\n", np.allclose(B_inv_inv, B))

# ---------------------------------------------------------------
# 6. Solving Systems of Linear Equations
# ---------------------------------------------------------------
def example_solve_linear_system():
    section_header("6. Solving Linear Systems (Ax = b)")

    # 2x + 3y = 8
    # 5x + 4y = 13
    A = np.array([[2, 3], [5, 4]])
    b = np.array([8, 13])

    x = np.linalg.solve(A, b)
    print("A:\n", A)
    print("b:\n", b)
    print("Solution x:\n", x)
    print("Check A @ x == b:\n", np.allclose(A @ x, b))


# Exercises:
# 6a. Solve the system:
#       x + y + z = 6
#       2y + 5z = -4
#       2x + 5y - z = 27
# 6b. Compare np.linalg.solve(A, b) with computing
#     np.linalg.inv(A) @ b. Which is generally preferred, and why?
#
# --- your code here ---
A = np.array([[1, 1, 1], [0, 2, 5], [2, 5, -1]])
B = np.array([6, -4, 27])
x = np.linalg.solve(A, B)
print("Matrix A:\n", A)
print("B:\n", B)
print("Solution x(Matrix 6a):\n", x)
print("Check A @ x == B:\n", np.allclose(A @ x, B))

A_inv = np.linalg.inv(A)
x_inv = A_inv @ B
print("Matrix A:\n", A)
print("B:\n", B)
print("Solution x:\n", x_inv)
# 6b. Compare np.linalg.solve(A, b) with computing
#     np.linalg.inv(A) @ b. Which is generally preferred, and why?
# np.linalg.solve(A, b) is generally preferred over np.linalg.inv(A) @ b.
# This is because `solve` uses more numerically stable and efficient algorithms
# (like LU decomposition) to directly find the solution without explicitly
# computing the inverse. Calculating the inverse first can be computationally
# more expensive and prone to greater numerical errors, especially for large
# or ill-conditioned matrices.

# ---------------------------------------------------------------
# 7. Eigenvalues and Eigenvectors
# ---------------------------------------------------------------
def example_eigen():
    section_header("7. Eigenvalues and Eigenvectors")

    A = np.array([[4, -2], [1, 1]])
    eigenvalues, eigenvectors = np.linalg.eig(A)

    print("A:\n", A)
    print("Eigenvalues:\n", eigenvalues)
    print("Eigenvectors (columns):\n", eigenvectors)


# Exercises:
# 7a. Verify A @ v == lambda * v for each eigenvalue/eigenvector pair.
# 7b. Find the eigenvalues of a diagonal matrix and explain the
#     pattern you notice.
#
# --- your code here ---
A = np.array([[4, -2], [1, 1]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Matrix A:\n",A)
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors (columns):\n", eigenvectors)
print("Check A @ v == lambda * v for each eigenvalue/eigenvector pair:")
for i in range(len(eigenvalues)):
    lambda_i = eigenvalues[i]
    v_i = eigenvectors[:, i]
    # np.allclose is used for floating point comparisons
    print(f"  For eigenvalue {lambda_i:.2f}: np.allclose(A @ v_i, lambda_i * v_i): {np.allclose(A @ v_i, lambda_i * v_i)}")

B = np.array([[2, 0], [0, 3]])
eigenvalues, eigenvectors = np.linalg.eig(B)
print("Matrix B:\n",B)
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors (columns):\n", eigenvectors)
# Pattern: The eigenvalues of a diagonal matrix are simply the diagonal entries
# of the matrix itself.

# ---------------------------------------------------------------
# 8. Norms (vector and matrix length/magnitude)
# ---------------------------------------------------------------
def example_norms():
    section_header("8. Norms")

    v = np.array([3, 4])
    l2_norm = np.linalg.norm(v)          # Euclidean norm
    l1_norm = np.linalg.norm(v, ord=1)   # Manhattan norm

    print("v:\n", v)
    print("L2 norm (Euclidean):\n", l2_norm)
    print("L1 norm (Manhattan):\n", l1_norm)


# Exercises:
# 8a. Compute the L2 norm of a 5-dimensional vector.
# 8b. Normalize a vector (divide by its own norm) so its length is 1,
#     and verify the result with np.linalg.norm.
#
# --- your code here ---
v = np.array([1, 2, 3, 4, 5])
l2_norm = np.linalg.norm(v)
print("8a. 5-dimensional vector:\n", v)
print("    L2 norm:\n", l2_norm)

v_normalized = v / l2_norm
l2_norm_normalized = np.linalg.norm(v_normalized)
print("8b. Normalized vector:\n", v_normalized)
print("    L2 norm of normalized vector:\n", l2_norm_normalized)

# ---------------------------------------------------------------
# 9. Rank of a Matrix
# ---------------------------------------------------------------
def example_rank():
    section_header("9. Matrix Rank")

    full_rank = np.array([[1, 2], [3, 4]])
    deficient_rank = np.array([[1, 2], [2, 4]])  # second row = 2 * first row

    print("Full-rank matrix:\n", full_rank, "-> rank =", np.linalg.matrix_rank(full_rank))
    print("Rank-deficient matrix:\n", deficient_rank, "-> rank =", np.linalg.matrix_rank(deficient_rank))


# Exercises:
# 9a. Construct a 4x4 matrix with rank 2.
# 9b. Explain (in a comment) the relationship between rank and
#     whether a matrix is invertible.
#
# --- your code here ---
r1 = np.array([1, 0, 0, 0])
r2 = np.array([0, 1, 0, 0])
r3 = 2 * r1 # A_matrix_rank = np.array([[1, 0, 0, 0], [0, 1, 0, 0], [2, 0, 0, 0], [0, 3, 0, 0]])
r4 = 3 * r2
A_matrix_rank = np.array([r1, r2, r3, r4])
print("9a. 4x4 Matrix with rank 2:\n", A_matrix_rank)
print("    Rank:\n", np.linalg.matrix_rank(A_matrix_rank))
# 9b. Explain (in a comment) the relationship between rank and
#     whether a matrix is invertible.
# A square matrix is invertible (non-singular) if and only if its rank
# is equal to its dimension (i.e., a full-rank matrix). If the rank is
# less than its dimension (rank-deficient), the matrix is singular and
# not invertible. This is because a full-rank matrix implies that all
# its rows (or columns) are linearly independent, which is a requirement
# for an inverse to exist.


# ---------------------------------------------------------------
# 10. Singular Value Decomposition (SVD)
# ---------------------------------------------------------------
def example_svd():
    section_header("10. Singular Value Decomposition (SVD)")

    A = np.array([[1, 2], [3, 4], [5, 6]])
    U, S, Vt = np.linalg.svd(A)

    print("A:\n", A)
    print("U:\n", U)
    print("Singular values S:\n", S)
    print("V^T:\n", Vt)

    # Reconstruct A from U, S, Vt to verify decomposition
    S_full = np.zeros(A.shape)
    np.fill_diagonal(S_full, S)
    A_reconstructed = U @ S_full @ Vt
    print("Reconstructed A:\n", A_reconstructed)


# Exercises:
# 10a. Reconstruct A from its SVD components and confirm it matches
#      the original (use np.allclose).
# 10b. Use SVD to compute a low-rank approximation of A by keeping
#      only the largest singular value. How close is it to A?
#
# --- your code here ---
A = np.array([[1, 2], [3, 4], [5, 6]])
U, S, Vt = np.linalg.svd(A)
S_full = np.zeros(A.shape)
np.fill_diagonal(S_full, S)
A_reconstructed = U @ S_full @ Vt
print("10a. Reconstructed A:\n", A_reconstructed)

A_low_rank = U[:, :1] @ np.diag(S[:1]) @ Vt[:1, :]
print("10b. Low-rank approximation of A:\n", A_low_rank)
print("Difference:\n",A - A_low_rank)



if __name__ == "__main__":
    example_create_arrays()
    example_matrix_multiplication()
    example_transpose()
    example_determinant()
    example_inverse()
    example_solve_linear_system()
    example_eigen()
    example_norms()
    example_rank()
    example_svd()


Matrix 1a:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Matrix 1b:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
Vector 1c:
 [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
Matrix 2a:
 [[2 4]
 [6 8]]
Matrix 2b:
 [[ 47  62  77  92]
 [ 59  78  97 116]
 [ 71  94 117 140]]
Shape of the result 2b
 (3, 4)
Matrix 3a:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Transpose of Matrix 3a:
 [[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]
Shape of transpose matrix 3a:
 (5, 3)
Matrix 3b:
 [[135 310 485]
 [150 350 550]
 [165 390 615]]
Shape of (A @ B).T:
 (3, 3)
B.T @ A.T:
 [[135 310 485]
 [150 350 550]
 [165 390 615]]
Shape of B.T @ A.T:
 (3, 3)
Matrix 4a:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Determinant of Matrix 4a:
 0.0
Matrix 4b:
 [[1 2 3]
 [4 5 6]
 [7 8 1]]
Determinant of Matrix 4b:
 23.999999999999993
Matrix 5a:
 [[1 2]
 [3 4]]
Inverse of Matrix 5a:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Matrix 5b:
 [[4 7]
 [2 6]]
Inverse of